--@AUTOR: CHAVEZ HERNANEZ, GUTIERREZ SILVESTRE, MARCELINO CISNEROS
--@FECHA CREACION: 10/04/23
--@DESCRIPCION: CREACION DE TABLAS DE LA PDB RESTAURANTE_S2: PLATILLOS Y BEBIDAS

PROMPT CREANDO TABLA CATEGORIA
CREATE TABLE CATEGORIA
(
  CATEGORIA_ID      NUMBER(10,0)    CONSTRAINT CATEGORIA_ID_PK PRIMARY KEY,
  CATEGORIA         VARCHAR2(200)   NOT NULL
);

PROMPT CREANDO TABLA RECETA
CREATE TABLE RECETA(
  RECETA_ID           NUMBER(10,0)    CONSTRAINT RECETA_ID_PK PRIMARY KEY,
  NOMBRE              VARCHAR2(200)    NOT NULL,
  PREPARACION         VARCHAR2(500)    NOT NULL,
  AUTOR               VARCHAR2(100)    NOT NULL,
  GRADO_DIFICULTAD    VARCHAR2(40)     NOT NULL
);

PROMPT CREANDO TABLA INGREDIENTE
CREATE TABLE INGREDIENTE(
  INGREDIENTE_ID    NUMBER(10,0)    CONSTRAINT INGREDIENTE_ID_PK PRIMARY KEY,   
  INGREDIENTE       VARCHAR2(50)    NOT NULL,
  UNIDAD_MEDIDA     VARCHAR2(20)    NOT NULL,
  CALORIAS          NUMBER(10,0)    NOT NULL
);

PROMPT CREANDO TABLA RECETA_INGREDIENTE
CREATE TABLE RECETA_INGREDIENTE(
  RECETA_INGREDIENTE_ID       NUMBER(10,0)    CONSTRAINT RECETA_INGREDIENTE_ID_PK PRIMARY KEY,  
  GLUTEN_FREE                 CHAR(1)         NOT NULL,
  CANTIDAD                    NUMBER(10,0)    NOT NULL,
  RECETA_ID                   NUMBER(10,0)    NOT NULL,
  INGREDIENTE_ID              NUMBER(10,0)    NOT NULL,
  CONSTRAINT RECETA_INGREDIENTE_INGREDIENTE_ID_FK FOREIGN KEY (INGREDIENTE_ID)
  REFERENCES INGREDIENTE(INGREDIENTE_ID),
  CONSTRAINT RECETA_INGREDIENTE_RECETA_ID_FK FOREIGN KEY (RECETA_ID)
  REFERENCES RECETA(RECETA_ID)
);

PROMPT CREANDO TABLA PLATILLO
CREATE TABLE PLATILLO(
  PLATILLO_ID     NUMBER(10,0)    CONSTRAINT PLATILLO_ID_PK PRIMARY KEY,
  NOMBRE          VARCHAR2(100)   NOT NULL,
  COSTO           NUMBER(5,0)     NOT NULL,
  FOTO            BLOB                NULL,
  CATEGORIA_ID    NUMBER(10,0)    NOT NULL,
  RECETA_ID       NUMBER(10,0)    NOT NULL,
  CONSTRAINT PLATILLO_CATEGORIA_ID_FK FOREIGN KEY (CATEGORIA_ID)
  REFERENCES CATEGORIA(CATEGORIA_ID),
  CONSTRAINT PLATILLO_RECETA_ID_FK FOREIGN KEY (RECETA_ID)
  REFERENCES RECETA(RECETA_ID)
);

PROMPT CREANDO TABLA BEBIDA
CREATE TABLE BEBIDA(
  BEBIDA_ID       NUMBER(10,0)    CONSTRAINT BEBIDA_ID_PK PRIMARY KEY,
  NOMBRE          VARCHAR2(100)   NOT NULL,
  COSTO           NUMBER(5,0)     NOT NULL,
  FOTO            BLOB                NULL,
  RECETA_ID       NUMBER(10,0)    NOT NULL,
  CONSTRAINT BEBIDA_RECETA_ID_FK FOREIGN KEY (RECETA_ID)
  REFERENCES RECETA(RECETA_ID)
);

PROMPT CREANDO TABLA COCINERO_PLATILLO
CREATE TABLE COCINERO_PLATILLO(
  COCINERO_PLATILLO_ID    NUMBER(10,0)    CONSTRAINT COCINERO_PLATILLO_ID_PK PRIMARY KEY,
  COSTO_EXTRA             VARCHAR2(10)    NOT NULL,
  CAMBIO_INGREDIENTE      CHAR(1)         NOT NULL,
  TIEMPO_PREPARACION_MIN  NUMBER(10,0)    NOT NULL,
  PLATILLO_ID             NUMBER(10,0)    NOT NULL,
  EMPLEADO_RID            NUMBER(10,0)    NOT NULL,
  CONSTRAINT COCINERO_PLATILLO_PLATILLO_ID_FK FOREIGN KEY (PLATILLO_ID)
  REFERENCES PLATILLO(PLATILLO_ID)
);

PROMPT CREANDO TABLA BARTENDER_BEBIDA
CREATE TABLE BARTENDER_BEBIDA(
  BARTENDER_BEBIDA_ID     NUMBER(10,0)    CONSTRAINT BARTENDER_BEBIDA_ID_PK PRIMARY KEY,
  TIEMPO_PREPARACION_MIN  NUMBER(10,0)    NOT NULL,
  BEBIDA_ID               NUMBER(10,0)    NOT NULL,
  EMPLEADO_RID            NUMBER(10,0)    NOT NULL,
  CONSTRAINT BARTENDER_BEBIDA_BEBIDA_ID_FK FOREIGN KEY (BEBIDA_ID)
  REFERENCES BEBIDA(BEBIDA_ID)
);

PROMPT CREANDO TABLA PLATILLO_CUENTA
CREATE TABLE PLATILLO_CUENTA(
  PLATILLO_CUENTA_ID             NUMBER(10,0)    CONSTRAINT PLATILLO_CUENTA_ID_PK PRIMARY KEY,
  CANTIDAD                       NUMBER(10,0)    NOT NULL,
  CUENTA_RID                     NUMBER(5,0)     NOT NULL,
  COCINERO_PLATILLO_ID           NUMBER(10,0)    NOT NULL,
  CONSTRAINT PLATILLO_CUENTA_COCINERO_PLATILLO_ID_FK FOREIGN KEY (COCINERO_PLATILLO_ID)
  REFERENCES COCINERO_PLATILLO(COCINERO_PLATILLO_ID)
);

PROMPT CREANDO TABLA BEBIDA_CUENTA
CREATE TABLE BEBIDA_CUENTA(
  BEBIDA_CUENTA_ID                NUMBER(10,0)    CONSTRAINT BEBIDA_CUENTA_ID_PK PRIMARY KEY,
  CANTIDAD                        NUMBER(10,0)    NOT NULL,
  CUENTA_RID                      NUMBER(5,0)     NOT NULL,
  BARTENDER_BEBIDA_ID             NUMBER(10,0)    NOT NULL,
  CONSTRAINT BEBIDA_CUENTA_BARTENDER_BEBIDA_ID_FK FOREIGN KEY (BARTENDER_BEBIDA_ID)
  REFERENCES BARTENDER_BEBIDA(BARTENDER_BEBIDA_ID)
);

PROMPT CREANDO INDICES
CREATE INDEX RECETA_NOMBRE_IX ON RECETA(NOMBRE);
CREATE INDEX PLATILLO_COSTO_IX ON PLATILLO(COSTO);
CREATE INDEX BEBIDA_COSTO_IX ON BEBIDA(COSTO);
CREATE INDEX PLATILLO_CUENTA_CUENTA_RID_IX ON PLATILLO_CUENTA(CUENTA_RID);
CREATE INDEX BARTENDER_BEBIDA_CUENTA_RID_IX ON BEBIDA_CUENTA(CUENTA_RID);